blank_issues_enabled: true
contact_links:
  - name: Umkoin Core Security Policy
    url: https://github.com/umkoin/umkoin/blob/master/SECURITY.md
    about: View security policy
  - name: Umkoin Core Developers
    url: http://www.umkoin.org
    about: Umkoin Core homepage
